server:
  port: 8600

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java
    username: root
    password: TranMinhVuong@10052000


  graphql:
    graphiql:
      enabled: true
      path: /graphiql